django/kursach/blog/urls.py
from django.urls import path
from blog.views import(

    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    download,
)

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit', edit_blog_view, name="edit"),
    path('download', download, name="download"),
]

django/kursach/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from blog import views
from django.conf.urls import url
from django.views.static import serve


from personal.views import (
    home_screen_view,
    program_screen_view,
)

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
	must_authenticate_view,
)

urlpatterns = [
    path('', home_screen_view, name="home"),
    path('account/', account_view, name="account"),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', 'blog')),
    path('login/', login_view, name="login"),
    path('logout/', logout_view, name="logout"),
	path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('register/', registration_view, name="register"),
    path('download', program_screen_view, name="download"),
    url(r'^download/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT}),


    
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/kursach/personal/models.py
from django.db import models


# PRIORITY = [
#     ("H", "Высокий"),
#     ("M", "Средний"),
#     ("L", "Низкий"),
# ]

# class Question(models.Model):
#     title = models.CharField(verbose_name = 'Заголовок', max_length=50)
#     question = models.TextField(verbose_name = 'Вопрос', max_length=500)
#     priority = models.CharField(verbose_name = 'Приоритет', max_length=1, choices=PRIORITY)    


#     def _str_(self):
#         return self.title

#     class Meta:
#         verbose_name = "Вопрос"
#         verbose_name_plural = "Вопрос"

django/kursach/personal/views.py
from django.shortcuts import render
from operator import attrgetter
from blog.models import BlogPost, Program


def home_screen_view(request):
    
    context = {}
    blog_posts = sorted(BlogPost.objects.all(), key=attrgetter('date_update'), reverse=True)
    context['blog_posts'] = blog_posts

    return render(request, "personal/home.html", context)

def program_screen_view(request):
    
    context = {}
    program_posts = sorted(Program.objects.all(), key=attrgetter('date_update'), reverse=True)
    context['program_posts'] = program_posts

    return render(request, "personal/download.html", context)

django/kursach/personal/templates/personal/download.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style type="text/css">

	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
</style>
<div class="container">
	<div class="row">


		<div class="left-column col-lg-10 offset-lg-1">


				<div class="card create-post-bar d-flex flex-column p-3">
					<p class="lead">Здесь вы можете выложить свои посты с ошибками или предложениями, если потребуется администратор свяжиться с вами по почте.</p>
				</div>


			{% for post in program_posts %}
				<div class="blog-post-container">
					{% include 'blog/snippets/program_post_snippet.html' with program_post=post %}
				</div>
			{% endfor %}
			
		</div>
		
		

	</div>
</div>

{% endblock content %}

django/kursach/personal/templates/personal/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style type="text/css">

	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
</style>
<div class="container">
	<div class="row">


		<div class="left-column col-lg-7 offset-lg-1">

			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3">
					<p class="lead">Здеь вы можете выложить свои посты с ошибками или предложениями, если потребуется администратор свяжиться с вами по почте.</p>
					<p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Создать пост</a></p>
				</div>
			</div>

			{% for post in blog_posts %}
				<div class="blog-post-container">
					{% include 'blog/snippets/blog_post_snippet.html' with blog_post=post %}
				</div>
			{% endfor %}
			
		</div>
		


		
		<div class="right-column col-lg-3 d-lg-flex d-none flex-column">

			<div class="card create-post-bar d-flex flex-column p-3">
				<p class="lead">Здеь вы можете выложить свои посты с ошибками или предложениями, если потребуется администратор свяжиться с вами по почте.</p>
				<p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Создать пост</a></p>
			</div>
		
		</div>
		

	</div>
</div>

{% endblock content %}